services:
  postgres:
    image: postgres:18.3
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${UTENTE_POSTGRES:?Variabile non definita} -d ${DB_POSTGRES:?Variabile non definita}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    environment:
      - POSTGRES_USER=${UTENTE_POSTGRES:?Variabile non definita}
      - POSTGRES_PASSWORD=${PASSWORD_POSTGRES:?Variabile non definita}
      - POSTGRES_DB=${DB_POSTGRES:?Variabile non definita}

  redis:
    image: redis:8.6.2
    restart: always
    command: >
      redis-server --requirepass ${PASSWORD_REDIS:?Variabile non definita}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${PASSWORD_REDIS:?Variabile non definita}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/docker/Dockerfile
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
    environment:
      - IN_DOCKER=true
      - UTENTE_POSTGRES=${UTENTE_POSTGRES:?Variabile non definita}
      - PASSWORD_POSTGRES=${PASSWORD_POSTGRES:?Variabile non definita}
      - DATABASE_POSTGRES=${DATABASE_POSTGRES:?Variabile non definita}
      - PASSWORD_REDIS=${PASSWORD_REDIS:?Variabile non definita}
