services:
  postgres:
    image: postgres:18.3
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${UTENTE_POSTGRES:-postgres} -d ${DB_POSTGRES:-mersenne}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    environment:
      - POSTGRES_USER=${UTENTE_POSTGRES:-postgres}
      - POSTGRES_PASSWORD=${PASSWORD_POSTGRES:-password}
      - POSTGRES_DB=${DB_POSTGRES:-mersenne}

  redis:
    image: redis:8.6.2
    restart: always
    command: >
      redis-server --requirepass ${PASSWORD_REDIS:-password}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${PASSWORD_REDIS:-password}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/docker/Dockerfile
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
