[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
    {id = "check-json"},
    {id = "check-toml"},
    {
        id = "check-yaml",
        args = ["--unsafe"]
    },
    {id = "check-shebang-scripts-are-executable"},
    {id = "check-symlinks"},
    {id = "end-of-file-fixer"},
    {id = "trailing-whitespace"}
]


[[repos]]
repo = "local"
hooks = [
    {
        id = "echo",
        name = "Elenca file modificati",
        entry = "echo",
        language = "system",
        types = ["text"]
    },
    {
        id = "ruff-check",
        name = "Esegui ruff check in seguito a modifiche nel backend",
        entry = "uv run ruff check --force-exclude --fix --exit-non-zero-on-fix",
        require_serial = true,
        language = "unsupported",
        types = ["python"],
        files = "^backend/.*$"
    },
    {
        id = "ruff-format",
        name = "Esegui ruff format in seguito a modifiche nel backend",
        entry = "uv run ruff format --force-exclude --exit-non-zero-on-format",
        require_serial = true,
        language = "unsupported",
        types = ["python"],
        files = "^backend/.*$"
    },
    {
        id = "ty-check",
        name = "Esegui ty check in seguito a modifiche nel backend",
        entry = "uv run ty check --error-on-warning",
        require_serial = true,
        language = "unsupported",
        types = ["python"],
        files = "^backend/.*$"
    },
    {
        id = "yamllint",
        name = "Esegui yamllint in seguito a modifiche nei file yaml",
        entry = "uv run yamllint -d '{extends: default, rules: {document-start: {present: false}, line-length: disable, truthy: {check-keys: false}}}'",
        language = "unsupported",
        types = ["text"],
        files = "\\.(yml|yaml)$"
    }
]
